"""Add discount.

Revision ID: 6781aafc4009
Revises: 931941ee8d96
Create Date: 2021-12-30 22:55:09.298600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6781aafc4009'
down_revision = '931941ee8d96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('discount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'discount')
    # ### end Alembic commands ###
