"""Add shop_id.

Revision ID: 6840fad90b47
Revises: 6781aafc4009
Create Date: 2021-12-30 23:11:42.281144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6840fad90b47'
down_revision = '6781aafc4009'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('shop_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'shop_id')
    # ### end Alembic commands ###
